[project]
name = "staticgen"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.5",
]

[project.scripts]
staticgen = "staticgen:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
